[package]
name = "sunholo/motoko_ext_herdr"
version = "0.1.0"
edition = "1"

[dependencies]
"sunholo/motoko_ext_abi" = { path = "../motoko-ext-abi" }

[effects]
max = ["Process", "FS", "Env", "IO", "Clock"]

[exports]
modules = [
  "sunholo/motoko_ext_herdr/register",
  "sunholo/motoko_ext_herdr/herdr",
  "sunholo/motoko_ext_herdr/types"
]
