#!/usr/bin/env python3
"""Emit src/core/ext/registry_generated.ail in the ABI 6.0 list shape.

ADR-001 Phase C, D10 (MOT-129). The upstream `ailang generate-extension-registry`
(v0.33.0) still emits the 5.x record shape (`Option[ExtensionHooks]`,
`with_id`, `{ hooks }`), so at 6.0 the registry file was hand-edited against
its own "do not edit" rule. This project-local generator replaces that
command for motoko_agent: it reads the same `[extensions]` table, keeps the
upstream derivations verbatim (short-name derivation, `pkg/` import prefix,
lockfile presence check, sorted effect row, module name from `output`), and
emits the 6.0 wiring:

  resolve(name, cfg) -> Option[[Capability]]
  parse_tokens builds ExtEntry through registry_normalize.normalize_registration;
    a rejection prints the rule and exit(2) (fail-closed, D10);
    an empty registration is omitted by name (D7)
  parse_core_ext_order -> ExtRegistry { entries }

Usage:
  python3 tools/ext_registry_gen/generate.py            # write [extensions].output
  python3 tools/ext_registry_gen/generate.py --dry-run  # print to stdout
  python3 tools/ext_registry_gen/generate.py --check    # exit 1 if the file on disk differs

The `[extensions]` keys it reads beyond the upstream ones:
  capability_import = "module/path.Capability"   (default: ABI types.Capability)
  entry_import      = "module/path.ExtEntry"     (default: ABI types.ExtEntry)
  normalize_import  = "module/path"              (default: src/core/ext/registry_normalize)
`hooks_import` is NOT read (upstream's manifest loader requires the key, so it
stays in ailang.toml; it names a 5.x type that no longer exists).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tomllib

DEFAULT_EFFECT_ROW = "Env, FS"  # upstream's historical fallback, kept for parity

HEADER = """-- GENERATED by tools/ext_registry_gen/generate.py (make registry_gen)
-- Source: ailang.toml [extensions]
-- Do not edit. Regenerate: make registry_gen   (verify: make registry_gen_check)
--
-- ABI 6.0 list shape (ADR-001 Phase C, D10). This file is generator-produced;
-- nothing in it is hand-diffed. Do NOT use the upstream
-- `ailang generate-extension-registry` (v0.33.0) here: it still emits the 5.x
-- record shape and its output does not type-check against the 6.0 ABI.
"""


def strip_version(ref: str) -> str:
    return ref.split("@", 1)[0]


def derive_short_name(ref: str) -> str:
    """Mirror of upstream deriveShortName.
    "sunholo/motoko_ext_exa_search@0.4.1" -> "exa_search"; "motoko-ext-x-y" -> "x_y"."""
    name = strip_version(ref)
    if "/" in name:
        name = name.split("/", 1)[1]
    for prefix in ("motoko-ext-", "motoko_ext_"):
        if name.startswith(prefix):
            name = name[len(prefix):]
    return name.replace("-", "_")


def split_import(ref: str, key: str) -> tuple[str, str]:
    dot = ref.rfind(".")
    if dot < 0:
        sys.exit(f"{key}: import ref {ref!r} must be in module/path.TypeName format")
    return ref[:dot], ref[dot + 1:]


def effect_row(ext_effects: list[str], max_effects: list[str]) -> str:
    row = ext_effects or max_effects
    if not row:
        return DEFAULT_EFFECT_ROW
    return ", ".join(sorted(row))


def render(manifest: dict, lock: dict) -> tuple[str, str]:
    ext = manifest.get("extensions") or {}
    packages = ext.get("packages") or []
    if not packages:
        sys.exit("no [extensions].packages in ailang.toml -- nothing to generate")

    locked = {p["name"] for p in lock.get("packages", [])}
    imports: list[tuple[str, str, str]] = []
    for ref in packages:
        name = strip_version(ref)
        if name not in locked:
            sys.exit(f"package {name!r} is listed in [extensions] but not found in ailang.lock -- run: ailang lock")
        prefix = "pkg/" if "/" in name else ""
        imports.append((prefix, name, derive_short_name(ref)))

    out_path = ext.get("output") or "registry_generated.ail"
    module_name = ext.get("module_name") or out_path.removesuffix(".ail")

    config_module, config_type = split_import(ext["config_import"], "config_import")
    cap_module, cap_type = split_import(
        ext.get("capability_import", "pkg/sunholo/motoko_ext_abi/types.Capability"), "capability_import")
    entry_module, entry_type = split_import(
        ext.get("entry_import", "pkg/sunholo/motoko_ext_abi/types.ExtEntry"), "entry_import")
    registry_module, registry_type = split_import(ext["registry_import"], "registry_import")
    normalize_module = ext.get("normalize_import", "src/core/ext/registry_normalize")
    row = effect_row(ext.get("effects") or [], (manifest.get("effects") or {}).get("max") or [])

    if cap_module == entry_module:
        abi_imports = f"import {cap_module} ({cap_type}, {entry_type})\n"
    else:
        abi_imports = f"import {cap_module} ({cap_type})\nimport {entry_module} ({entry_type})\n"

    lines = [HEADER, "\n", f"module {module_name}\n", "\n"]
    for prefix, name, alias in imports:
        lines.append(f"import {prefix}{name}/register (register_with_config as register_{alias})\n")
    lines.append(f"import {config_module} ({config_type})\n")
    lines.append(abi_imports)
    lines.append(f"import {registry_module} ({registry_type})\n")
    lines.append(f"import {normalize_module} (normalize_registration, rejection_message)\n")
    lines.append("import std/string (split, trim)\n")
    lines.append("import std/option (Option, Some, None)\n")
    lines.append("import std/result (Ok, Err)\n")
    lines.append("import std/list as List (length)\n")
    lines.append("import std/io (println, exit)\n")
    lines.append("\n")

    lines.append(f"func resolve(name: string, cfg: {config_type}) -> Option[[{cap_type}]] ! {{{row}}} {{\n")
    for i, (_, _, alias) in enumerate(imports):
        kw = "else if" if i else "if"
        lines.append(f'  {kw} name == "{alias}" then Some(register_{alias}(cfg))\n')
    lines.append("  else None\n}\n\n")

    lines.append(f"""-- B8: the registration boundary. Every resolved list goes through
-- `normalize_registration` (D3 votes, D3 disjoint provider names, D4 fold
-- repeats, D7 empty). A rejection FAILS THE BUILD -- printed and exit 2 --
-- because silently omitting a mis-registered extension while the others load
-- is the fail-open shape [AR-codex "Missed"]. An EMPTY registration is
-- omitted by name (D7, recommended reading), never silently.
func parse_tokens(xs: [string], idx: int, acc: [{entry_type}], cfg: {config_type}) -> {registry_type} ! {{{row}}} {{
  match xs {{
    [] => {{ entries: acc }},
    raw :: rest => {{
      let name = trim(raw);
      match resolve(name, cfg) {{
        None => parse_tokens(rest, idx + 1, acc, cfg),
        Some(caps) => {{
          let id = "${{name}}#${{show(idx)}}";
          match normalize_registration(id, caps) {{
            Err(e) => {{
              let _ = println("extension registry rejected: ${{rejection_message(e)}}");
              let _ = exit(2);
              {{ entries: acc }}
            }},
            Ok(entry) =>
              if List.length(entry.caps) == 0 then {{
                let _ = println("extension '${{id}}' registers no capability atom; omitted from the registry (D7)");
                parse_tokens(rest, idx + 1, acc, cfg)
              }} else parse_tokens(rest, idx + 1, acc ++ [entry], cfg)
          }}
        }}
      }}
    }}
  }}
}}

export func parse_core_ext_order(raw: string, cfg: {config_type}) -> {registry_type} ! {{{row}}} {{
  if trim(raw) == "" then {{ entries: [] }}
  else parse_tokens(split(raw, ","), 0, [], cfg)
}}
""")
    return out_path, "".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="ailang.toml")
    ap.add_argument("--output", default="", help="override write path (module name still comes from ailang.toml)")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--check", action="store_true", help="exit 1 if the file on disk differs from the generator's output")
    a = ap.parse_args()

    with open(a.config, "rb") as f:
        manifest = tomllib.load(f)
    lock_path = os.path.join(os.path.dirname(a.config) or ".", "ailang.lock")
    with open(lock_path, "rb") as f:
        lock = json.load(f)

    out_path, text = render(manifest, lock)
    if a.output:
        out_path = a.output
    if a.dry_run:
        sys.stdout.write(text)
        return 0
    if a.check:
        try:
            with open(out_path, encoding="utf-8") as f:
                on_disk = f.read()
        except FileNotFoundError:
            on_disk = None
        if on_disk == text:
            print(f"  ✓ {out_path} matches the generator")
            return 0
        print(f"  ✗ {out_path} differs from the generator -- run: make registry_gen", file=sys.stderr)
        return 1
    tmp = out_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.replace(tmp, out_path)
    print(f"generated {out_path} ({len(manifest['extensions']['packages'])} packages)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
