#!/usr/bin/env bash
# 031 PLAN-001 P1.1: type-check / test src/core modules against THIS checkout's
# ABI 8.0 package in a throwaway workspace. Run from a repo root:
#   p11_core_check.sh check <module.ail>...   ailang check each; exit 1 on any failure
#   p11_core_check.sh test  <module.ail>...   ailang test each; the count line is
#                                             parsed and "0 failed" is required
#
# WHY A WORKSPACE, AND WHY IT IS IMMUNE TO THE ailang.lock TRAP. The repo's
# ailang.lock pins every path dependency to the PRIMARY checkout's absolute
# path, so a check inside a clone resolves the primary's packages (the trap
# P0.4, P0.5 and P0.2b each hit). This script never reads that lock: it copies
# the cwd's src/core (.ail files only), ABI package and conformance kit into a
# fresh directory whose ailang.toml names only path dependencies INSIDE that
# directory, and runs `ailang lock` there. Nothing resolves to the primary, so
# a mutation applied to the cwd's src/core is what gets checked.
#
# WHY THE TREE CANNOT BE CHECKED IN PLACE UNTIL P1.2. `ext/runtime.ail` imports
# `ext/registry_generated.ail`, which imports all 18 extension packages, and
# `tool_phase.ail` (hence `session.ail`) imports `motoko_ext_scratchpad/
# ws_loopback`; every one of those is 7.4 until P1.2 and fails to type-check
# against the 8.0 ABI inside the first package. Two stand-ins replace them
# here, and nothing else is stubbed:
#   * the registry is GENERATED by the real template
#     (tools/ext_registry_gen/generate.py, P0.5's) over ONE synthetic 8.0
#     extension (deps/motoko-ext-p11stub), so the generated file, the
#     three-argument `normalize_registration` and the runtime are checked
#     together, exactly as the tree will be at R-G;
#   * `ws_loopback.exec_scratchpad_cell_ws` is a signature-identical stub
#     returning a failed CellExecResult (exit -1). tool_phase.ail calls it;
#     nothing here executes it.
set -uo pipefail
mode="${1:-}"; shift || true
{ [ "$mode" = check ] || [ "$mode" = test ]; } && [ $# -ge 1 ] \
  || { echo "usage: $0 check|test <module.ail>..." >&2; exit 2; }
R=$(pwd)
T=$(mktemp -d "${TMPDIR:-/tmp}/p11ws.XXXXXX"); trap 'rm -rf "$T"' EXIT
mkdir -p "$T/deps/motoko-ext-abi" "$T/deps/motoko_ext_conformance/fixtures" \
         "$T/deps/motoko-ext-p11stub" "$T/deps/motoko-ext-scratchpad"
cp packages/motoko-ext-abi/types.ail packages/motoko-ext-abi/ailang.toml "$T/deps/motoko-ext-abi/"
cp packages/motoko_ext_conformance/ailang.toml packages/motoko_ext_conformance/invariants.ail \
   packages/motoko_ext_conformance/harness.ail "$T/deps/motoko_ext_conformance/"
cp packages/motoko_ext_conformance/fixtures/reject_fixtures.ail "$T/deps/motoko_ext_conformance/fixtures/"
( cd src && find core -name '*.ail' -print0 | while IFS= read -r -d '' f; do
    mkdir -p "$T/src/$(dirname "$f")"; cp "$f" "$T/src/$f"; done )

cat > "$T/deps/motoko-ext-p11stub/ailang.toml" <<'TOML'
[package]
name = "sunholo/motoko_ext_p11stub"
version = "0.1.0"
edition = "1"
ailang = ">=0.33.0"

[dependencies]
"sunholo/motoko_ext_abi" = { path = "../motoko-ext-abi" }

[exports]
modules = ["sunholo/motoko_ext_p11stub/register"]
TOML
cat > "$T/deps/motoko-ext-p11stub/register.ail" <<'AIL'
-- P1.1 workspace stand-in: one synthetic 8.0 extension so the real registry
-- template has something to generate over. Registers nothing.
module sunholo/motoko_ext_p11stub/register

import std/json (jo)
import pkg/sunholo/motoko_ext_abi/types (ExtRegistration)

export func register_with_config(_cfg: a) -> ExtRegistration {
  { config: jo([]), caps: [] }
}
AIL

cat > "$T/deps/motoko-ext-scratchpad/ailang.toml" <<'TOML'
[package]
name = "sunholo/motoko_ext_scratchpad"
version = "0.1.0"
edition = "1"
ailang = ">=0.33.0"

[dependencies]
"sunholo/motoko_ext_abi" = { path = "../motoko-ext-abi" }

[exports]
modules = ["sunholo/motoko_ext_scratchpad/ws_loopback"]
TOML
cat > "$T/deps/motoko-ext-scratchpad/ws_loopback.ail" <<'AIL'
-- P1.1 workspace stand-in for packages/motoko_scratchpad/ws_loopback.ail (7.4
-- until P1.2): the one export tool_phase.ail imports, signature-identical,
-- executing nothing.
module sunholo/motoko_ext_scratchpad/ws_loopback

import std/json (Json, jo)
import pkg/sunholo/motoko_ext_abi/types (ExtCtx, ExtRuntime)
import src/core/tool_contract (ToolCallEnvelope)
import src/core/types (CellExecResult)

export func exec_scratchpad_cell_ws(_rt: ExtRuntime, _ctx: ExtCtx, _call: ToolCallEnvelope, _cells: Json, _timeout_secs: int) -> CellExecResult ! {AI, Clock, Env, FS, IO, Net, Process, SharedMem, Stream, Rand} {
  { stdout: "", stderr: "p11 stand-in: no scratchpad in this workspace", exit_code: -1, metadata: jo([]) }
}
AIL

cat > "$T/ailang.toml" <<'TOML'
[package]
name = "local/p11core"
version = "0.1.0"
edition = "1"
module_prefix = "src"
ailang = ">=0.33.0"

[dependencies]
"sunholo/motoko_ext_abi" = { path = "deps/motoko-ext-abi" }
"sunholo/motoko_ext_conformance" = { path = "deps/motoko_ext_conformance" }
"sunholo/motoko_ext_p11stub" = { path = "deps/motoko-ext-p11stub" }
"sunholo/motoko_ext_scratchpad" = { path = "deps/motoko-ext-scratchpad" }

[extensions]
packages = ["sunholo/motoko_ext_p11stub@0.1.0"]
config_import = "src/core/config.RuntimeConfig"
hooks_import = "pkg/sunholo/motoko_ext_abi/types.ExtensionHooks"
capability_import = "pkg/sunholo/motoko_ext_abi/types.Capability"
entry_import = "pkg/sunholo/motoko_ext_abi/types.ExtEntry"
normalize_import = "src/core/ext/registry_normalize"
registry_import = "pkg/sunholo/motoko_ext_abi/types.ExtRegistry"
output = "src/core/ext/registry_generated.ail"
effects = ["AI", "Clock", "Env", "FS", "IO", "Net", "Process", "Rand", "SharedMem", "Stream", "Trace"]

[effects]
max = ["IO", "Env", "AI", "Net", "FS", "Process", "SharedMem", "Clock", "Stream", "SharedIndex", "Rand", "Trace"]
TOML

cd "$T"
ailang lock > lock.log 2>&1 || { tail -5 lock.log; echo "p11: ailang lock failed in the workspace"; exit 1; }
python3 "$R/tools/ext_registry_gen/generate.py" --config ailang.toml > gen.log 2>&1 \
  || { tail -5 gen.log; echo "p11: registry generation failed"; exit 1; }

strip() { sed -E 's/\x1b\[[0-9;]*[a-zA-Z]//g' | grep -v -E '^(Warning: dependency|Run .ailang lock.)'; }
fail=0
for m in "$@"; do
  [ -f "$m" ] || { echo "p11: no such module in the workspace: $m"; fail=1; continue; }
  if [ "$mode" = check ]; then
    out=$(ailang check "$m" 2>&1); rc=$?
    if [ $rc -eq 0 ]; then echo "p11: check $m ok"
    else echo "$out" | strip | tail -8; echo "p11: check $m FAILED (exit $rc)"; fail=1; fi
  else
    # P11_ALLOW_SKIPS=1 passes --allow-skips: a module whose contract
    # properties have no generator (exit_manifest.ail, pre-existing) otherwise
    # exits 1 with "0 failed"; the count line is still parsed and required.
    out=$(ailang test ${P11_ALLOW_SKIPS:+--allow-skips} "$m" 2>&1); rc=$?
    line=$(echo "$out" | strip | grep -E '^[0-9]+ tests:' | tail -1)
    # A here-string, not `echo | grep -q`: under pipefail an early-exiting grep
    # can SIGPIPE the writer and score a green run red (the P0.3 mutgate trap).
    if [ $rc -eq 0 ] && grep -qE '^[0-9]+ tests: [0-9]+ passed, 0 failed' <<<"$out"; then
      echo "p11: test $m ok -- $line"
    else
      echo "$out" | strip | grep -E 'FAIL|Error|error|tests:' | tail -12; echo "p11: test $m FAILED (exit $rc; $line)"; fail=1
    fi
  fi
done
exit $fail
