[package]
name = "sunholo/motoko_compose"
version = "0.1.0"
edition = "1"
module_prefix = "src"

[exports]
modules = ["src/core/ext/compose/compose"]

[dependencies]
"sunholo/motoko_core" = { path = "../.." }

[effects]
max = ["IO", "FS", "AI", "Process", "Env", "Clock", "SharedMem"]
