#!/usr/bin/env bash
# 031 PLAN-001 P1.2c: type-check / run the files batch C owns under the operator's
# masked-files ruling (PLAN-001 §3 P1.2) -- scripts/dst/conformance_selftest.ail and
# scripts/dst/long_qwen_compaction_dst.ail, both of which import compaction_ai -- against
# the COMMITTED ABI 8.0 and core, batch A's committed packages, and batch C's five packages
# as they stand in the cwd, in a throwaway workspace. Run from a repo root:
#   p12c_core_check.sh check <module.ail>...     ailang check each; exit 1 on any failure
#   p12c_core_check.sh run   <module.ail> [caps] ailang run --ai-stub --entry main
#   P11_RELAX=1     sets AILANG_RELAX_MODULES=1 (scripts/ declare module names that do
#                   not match their paths)
#
# Derived from evidence/P1.2a/p12a_core_check.sh, with ONE deliberate difference (PLAN-001
# §0 item 13, operator ruling 2026-09-21): everything that is not batch C's own surface
# comes from COMMITTED HEAD via `git archive HEAD` -- src/core, src/eval, scripts/, tools/,
# the ABI, the conformance kit and batch A's six packages -- never from the checkout, where
# P1.3r is editing src/core/ext/runtime.ail and other batches are editing packages/. Batch
# C's five packages and the two masked files are the cwd's (this part's surface; in a
# mutgate throwaway, the mutated bytes). The registry is generated by the real template
# over the eleven 8.0 packages (batch A + batch C); the other seven extensions are 7.4 until
# batches B and D and are not in the workspace registry. The scratchpad stand-in is P1.1's
# (tool_phase.ail imports it; nothing here runs it).
set -uo pipefail
mode="${1:-}"; shift || true
{ [ "$mode" = check ] || [ "$mode" = run ]; } && [ $# -ge 1 ] \
  || { echo "usage: $0 check <module.ail>... | run <module.ail> [caps]" >&2; exit 2; }
RUN_CAPS=""
if [ "$mode" = run ]; then RUN_CAPS="${2:-IO}"; set -- "$1"; fi
R=$(pwd)
T=$(mktemp -d "${TMPDIR:-/tmp}/p12ccore.XXXXXX")
# P12C_KEEP=1 keeps the workspace for inspection (its path is printed); default: removed.
if [ -n "${P12C_KEEP:-}" ]; then echo "p12c: workspace kept at $T"; else trap 'rm -rf "$T"' EXIT; fi
PKGS_A="motoko-ext-compaction-structural motoko-ext-decision-framework motoko-ext-empty-stop-guard motoko-ext-microrag motoko-ext-omnigraph motoko-ext-progress-contract-guard"
PKGS_C="motoko-ext-a2a motoko-ext-agentcli motoko-ext-ailang-docs motoko-ext-mcp motoko-ext-compaction-ai"
MASKED="scripts/dst/conformance_selftest.ail scripts/dst/long_qwen_compaction_dst.ail"
# P12C_REV=<rev> takes the committed surfaces from <rev> instead of HEAD (attribution runs).
REV="${P12C_REV:-HEAD}"
H="$T/head"; mkdir -p "$H"
git archive "$REV" src/core src/eval scripts tools packages/motoko-ext-abi packages/motoko_ext_conformance \
  $(for p in $PKGS_A; do echo packages/$p; done) | tar -x -C "$H" \
  || { echo "p12c: git archive $REV failed"; exit 1; }
mkdir -p "$T/deps/motoko-ext-abi" "$T/deps/motoko_ext_conformance/fixtures" "$T/deps/motoko-ext-scratchpad"
deps=""; exts=""
for p in $PKGS_A $PKGS_C; do
  case " $PKGS_C " in *" $p "*) SRC=packages/$p ;; *) SRC="$H/packages/$p" ;; esac
  mkdir -p "$T/deps/$p"; cp $SRC/*.ail $SRC/ailang.toml "$T/deps/$p/"
  name=$(sed -nE 's/^name = "(.*)"/\1/p' "$SRC/ailang.toml" | head -1)
  ver=$(sed -nE 's/^version = "(.*)"/\1/p' "$SRC/ailang.toml" | head -1)
  deps="$deps
\"$name\" = { path = \"deps/$p\" }"
  exts="$exts\"$name@$ver\", "
done
cp $H/packages/motoko-ext-abi/types.ail $H/packages/motoko-ext-abi/ailang.toml "$T/deps/motoko-ext-abi/"
cp $H/packages/motoko_ext_conformance/ailang.toml $H/packages/motoko_ext_conformance/invariants.ail \
   $H/packages/motoko_ext_conformance/harness.ail "$T/deps/motoko_ext_conformance/"
cp $H/packages/motoko_ext_conformance/fixtures/reject_fixtures.ail "$T/deps/motoko_ext_conformance/fixtures/"
( cd "$H/src" && find core eval -name '*.ail' -print0 2>/dev/null | while IFS= read -r -d '' f; do
    mkdir -p "$T/src/$(dirname "$f")"; cp "$f" "$T/src/$f"; done )  # src/eval: scripts/eval imports it
for top in scripts tools; do
  ( cd "$H" && find "$top" -name '*.ail' -print0 ) | while IFS= read -r -d '' f; do
    mkdir -p "$T/$(dirname "$f")"; cp "$H/$f" "$T/$f"; done
done
# the masked files are this part's surface: the cwd's bytes over HEAD's
for f in $MASKED; do cp "$f" "$T/$f"; done
# this part's evidence probes that compile against core (the cwd's)
mkdir -p "$T/scripts/p12c"; cp .agent/projects/031_system_one_decisions/evidence/P1.2c/p12c_calib_parity.ail "$T/scripts/p12c/"
# Scripts checked below compile from a COLD cache (none exists in a fresh workspace):
# on the pin, a warm cache can hide a cross-module type-name collision (README).

cat > "$T/deps/motoko-ext-scratchpad/ailang.toml" <<'TOML'
[package]
name = "sunholo/motoko_ext_scratchpad"
version = "0.1.0"
edition = "1"
ailang = ">=0.33.0"

[dependencies]
"sunholo/motoko_ext_abi" = { path = "../motoko-ext-abi" }

[exports]
modules = ["sunholo/motoko_ext_scratchpad/ws_loopback"]
TOML
cat > "$T/deps/motoko-ext-scratchpad/ws_loopback.ail" <<'AIL'
-- P1.2c workspace stand-in (P1.1's) for packages/motoko_scratchpad/ws_loopback.ail
-- (7.4 until batch B): the one export tool_phase.ail imports, signature-identical,
-- executing nothing.
module sunholo/motoko_ext_scratchpad/ws_loopback

import std/json (Json, jo)
import pkg/sunholo/motoko_ext_abi/types (ExtCtx, ExtRuntime)
import src/core/tool_contract (ToolCallEnvelope)
import src/core/types (CellExecResult)

export func exec_scratchpad_cell_ws(_rt: ExtRuntime, _ctx: ExtCtx, _call: ToolCallEnvelope, _cells: Json, _timeout_secs: int) -> CellExecResult ! {AI, Clock, Env, FS, IO, Net, Process, SharedMem, Stream, Rand} {
  { stdout: "", stderr: "p11 stand-in: no scratchpad in this workspace", exit_code: -1, metadata: jo([]) }
}
AIL

cat > "$T/ailang.toml" <<TOML
[package]
name = "local/p12ccore"
version = "0.1.0"
edition = "1"
module_prefix = "src"
ailang = ">=0.33.0"

[dependencies]
"sunholo/motoko_ext_abi" = { path = "deps/motoko-ext-abi" }
"sunholo/motoko_ext_conformance" = { path = "deps/motoko_ext_conformance" }
"sunholo/motoko_ext_scratchpad" = { path = "deps/motoko-ext-scratchpad" }$deps

[extensions]
packages = [${exts%, }]
config_import = "src/core/config.RuntimeConfig"
hooks_import = "pkg/sunholo/motoko_ext_abi/types.ExtensionHooks"
capability_import = "pkg/sunholo/motoko_ext_abi/types.Capability"
entry_import = "pkg/sunholo/motoko_ext_abi/types.ExtEntry"
normalize_import = "src/core/ext/registry_normalize"
registry_import = "pkg/sunholo/motoko_ext_abi/types.ExtRegistry"
output = "src/core/ext/registry_generated.ail"
effects = ["AI", "Clock", "Env", "FS", "IO", "Net", "Process", "Rand", "SharedMem", "Stream", "Trace"]

[effects]
max = ["IO", "Env", "AI", "Net", "FS", "Process", "SharedMem", "Clock", "Stream", "SharedIndex", "Rand", "Trace"]
TOML

# Scripts write run artifacts under a cwd-relative .ailang/ (present in the
# repo, absent from a fresh workspace).
mkdir -p "$T/.ailang"
cd "$T"
ailang lock > lock.log 2>&1 || { tail -5 lock.log; echo "p12c: ailang lock failed in the workspace"; exit 1; }
python3 "$H/tools/ext_registry_gen/generate.py" --config ailang.toml > gen.log 2>&1 \
  || { tail -5 gen.log; echo "p12c: registry generation failed"; exit 1; }

strip() { sed -E 's/\x1b\[[0-9;]*[a-zA-Z]//g' | grep -v -E '^(Warning: dependency|Run .ailang lock.)'; }
[ -n "${P11_RELAX:-}" ] && export AILANG_RELAX_MODULES=1
fail=0
for m in "$@"; do
  [ -f "$m" ] || { echo "p12c: no such module in the workspace: $m"; fail=1; continue; }
  if [ "$mode" = check ]; then
    out=$(ailang check "$m" 2>&1); rc=$?
    if [ $rc -eq 0 ]; then echo "p12c: check $m ok"
    else
      first=$(echo "$out" | strip | grep -m1 -E 'Error|PAT_|PAR_|LDR0|MOD0|TC0|EFF' | cut -c1-400)
      echo "$out" | strip | tail -8; echo "p12c: check $m FAILED (exit $rc): ${first}"; fail=1
    fi
  elif [ "$mode" = run ]; then
    out=$(ailang run --caps "$RUN_CAPS" --ai-stub --entry main "$m" 2>&1); rc=$?
    echo "$out" | strip | grep -v -E '^(→|✓ Running|WARNING MOD010|  Auto-relaxed|  Running under)' | tail -12
    if [ $rc -eq 0 ]; then echo "p12c: run $m ok"
    else echo "$out" | strip | tail -6; echo "p12c: run $m FAILED (exit $rc)"; fail=1; fi
  else
    # P11_ALLOW_SKIPS=1 passes --allow-skips: a module whose contract
    # properties have no generator (exit_manifest.ail, pre-existing) otherwise
    # exits 1 with "0 failed"; the count line is still parsed and required.
    out=$(ailang test ${P11_ALLOW_SKIPS:+--allow-skips} "$m" 2>&1); rc=$?
    line=$(echo "$out" | strip | grep -E '^[0-9]+ tests:' | tail -1)
    # A here-string, not `echo | grep -q`: under pipefail an early-exiting grep
    # can SIGPIPE the writer and score a green run red (the P0.3 mutgate trap).
    if [ $rc -eq 0 ] && grep -qE '^[0-9]+ tests: [0-9]+ passed, 0 failed' <<<"$out"; then
      echo "p12c: test $m ok -- $line"
    else
      echo "$out" | strip | grep -E 'FAIL|Error|error|tests:' | tail -12; echo "p12c: test $m FAILED (exit $rc; $line)"; fail=1
    fi
  fi
done
exit $fail
