#!/usr/bin/env bash
# 031 PLAN-001 P1.2a: type-check / test the files batch A owns under the operator's
# masked-files ruling (PLAN-001 §3 P1.2, 68791469) -- src/core/test/integration_tests.ail
# and four scripts that import compaction_structural / empty_stop_guard -- against
# THIS checkout's ABI 8.0 package AND batch A's six 8.0 packages, in a throwaway
# workspace. Run from a repo root:
#   p12a_core_check.sh check <module.ail>...   ailang check each; exit 1 on any failure
#   p12a_core_check.sh test  <module.ail>...   ailang test each; "0 failed" required
#   p12a_core_check.sh run   <module.ail> [caps]  ailang run --ai-stub --entry main
#                                              with --caps [caps] (default IO); exit kept
#   P11_RELAX=1     sets AILANG_RELAX_MODULES=1 (scripts/ declare module names that do
#                   not match their paths)
#
# Derived from evidence/P1.1/p11_core_check.sh (same ailang.lock-trap immunity: the
# cwd's src/core, scripts/, ABI, conformance kit and packages are COPIED into a fresh
# directory whose ailang.toml names only path dependencies inside it). One difference:
# the registry is generated by the real template over batch A's SIX REAL 8.0
# packages instead of P1.1's synthetic stub, so everything that reaches
# ext/registry_generated.ail is checked against the migrated extensions. The other
# twelve extensions are 7.4 until batches B-D and are simply not in the workspace
# registry; the one remaining stand-in is P1.1's signature-identical
# `ws_loopback.exec_scratchpad_cell_ws` (tool_phase.ail imports it; nothing here runs it).
set -uo pipefail
mode="${1:-}"; shift || true
{ [ "$mode" = check ] || [ "$mode" = test ] || [ "$mode" = run ]; } && [ $# -ge 1 ] \
  || { echo "usage: $0 check|test <module.ail>... | run <module.ail> [caps]" >&2; exit 2; }
RUN_CAPS=""
if [ "$mode" = run ]; then RUN_CAPS="${2:-IO}"; set -- "$1"; fi
R=$(pwd)
T=$(mktemp -d "${TMPDIR:-/tmp}/p12acore.XXXXXX"); trap 'rm -rf "$T"' EXIT
PKGS="motoko-ext-compaction-structural motoko-ext-decision-framework motoko-ext-empty-stop-guard motoko-ext-microrag motoko-ext-omnigraph motoko-ext-progress-contract-guard"
mkdir -p "$T/deps/motoko-ext-abi" "$T/deps/motoko_ext_conformance/fixtures" "$T/deps/motoko-ext-scratchpad"
deps=""; exts=""
for p in $PKGS; do
  mkdir -p "$T/deps/$p"; cp packages/$p/*.ail packages/$p/ailang.toml "$T/deps/$p/"
  name=$(sed -nE 's/^name = "(.*)"/\1/p' "packages/$p/ailang.toml" | head -1)
  ver=$(sed -nE 's/^version = "(.*)"/\1/p' "packages/$p/ailang.toml" | head -1)
  deps="$deps
\"$name\" = { path = \"deps/$p\" }"
  exts="$exts\"$name@$ver\", "
done
cp packages/motoko-ext-abi/types.ail packages/motoko-ext-abi/ailang.toml "$T/deps/motoko-ext-abi/"
cp packages/motoko_ext_conformance/ailang.toml packages/motoko_ext_conformance/invariants.ail \
   packages/motoko_ext_conformance/harness.ail "$T/deps/motoko_ext_conformance/"
cp packages/motoko_ext_conformance/fixtures/reject_fixtures.ail "$T/deps/motoko_ext_conformance/fixtures/"
( cd src && find core eval -name '*.ail' -print0 2>/dev/null | while IFS= read -r -d '' f; do
    mkdir -p "$T/src/$(dirname "$f")"; cp "$f" "$T/src/$f"; done )  # src/eval: scripts/eval imports it
# scripts/ and tools/ .ail files, so the type-driven inventory can check them in
# the same workspace; nothing under src/core imports them
for top in scripts tools; do
  [ -d "$top" ] && find "$top" -name '*.ail' -print0 | while IFS= read -r -d '' f; do
    mkdir -p "$T/$(dirname "$f")"; cp "$f" "$T/$f"; done
done

cat > "$T/deps/motoko-ext-scratchpad/ailang.toml" <<'TOML'
[package]
name = "sunholo/motoko_ext_scratchpad"
version = "0.1.0"
edition = "1"
ailang = ">=0.33.0"

[dependencies]
"sunholo/motoko_ext_abi" = { path = "../motoko-ext-abi" }

[exports]
modules = ["sunholo/motoko_ext_scratchpad/ws_loopback"]
TOML
cat > "$T/deps/motoko-ext-scratchpad/ws_loopback.ail" <<'AIL'
-- P1.2a workspace stand-in (P1.1's) for packages/motoko_scratchpad/ws_loopback.ail
-- (7.4 until batch B): the one export tool_phase.ail imports, signature-identical,
-- executing nothing.
module sunholo/motoko_ext_scratchpad/ws_loopback

import std/json (Json, jo)
import pkg/sunholo/motoko_ext_abi/types (ExtCtx, ExtRuntime)
import src/core/tool_contract (ToolCallEnvelope)
import src/core/types (CellExecResult)

export func exec_scratchpad_cell_ws(_rt: ExtRuntime, _ctx: ExtCtx, _call: ToolCallEnvelope, _cells: Json, _timeout_secs: int) -> CellExecResult ! {AI, Clock, Env, FS, IO, Net, Process, SharedMem, Stream, Rand} {
  { stdout: "", stderr: "p11 stand-in: no scratchpad in this workspace", exit_code: -1, metadata: jo([]) }
}
AIL

cat > "$T/ailang.toml" <<TOML
[package]
name = "local/p12acore"
version = "0.1.0"
edition = "1"
module_prefix = "src"
ailang = ">=0.33.0"

[dependencies]
"sunholo/motoko_ext_abi" = { path = "deps/motoko-ext-abi" }
"sunholo/motoko_ext_conformance" = { path = "deps/motoko_ext_conformance" }
"sunholo/motoko_ext_scratchpad" = { path = "deps/motoko-ext-scratchpad" }$deps

[extensions]
packages = [${exts%, }]
config_import = "src/core/config.RuntimeConfig"
hooks_import = "pkg/sunholo/motoko_ext_abi/types.ExtensionHooks"
capability_import = "pkg/sunholo/motoko_ext_abi/types.Capability"
entry_import = "pkg/sunholo/motoko_ext_abi/types.ExtEntry"
normalize_import = "src/core/ext/registry_normalize"
registry_import = "pkg/sunholo/motoko_ext_abi/types.ExtRegistry"
output = "src/core/ext/registry_generated.ail"
effects = ["AI", "Clock", "Env", "FS", "IO", "Net", "Process", "Rand", "SharedMem", "Stream", "Trace"]

[effects]
max = ["IO", "Env", "AI", "Net", "FS", "Process", "SharedMem", "Clock", "Stream", "SharedIndex", "Rand", "Trace"]
TOML

# Scripts write run artifacts under a cwd-relative .ailang/ (present in the
# repo, absent from a fresh workspace).
mkdir -p "$T/.ailang"
cd "$T"
ailang lock > lock.log 2>&1 || { tail -5 lock.log; echo "p12a: ailang lock failed in the workspace"; exit 1; }
python3 "$R/tools/ext_registry_gen/generate.py" --config ailang.toml > gen.log 2>&1 \
  || { tail -5 gen.log; echo "p12a: registry generation failed"; exit 1; }

strip() { sed -E 's/\x1b\[[0-9;]*[a-zA-Z]//g' | grep -v -E '^(Warning: dependency|Run .ailang lock.)'; }
[ -n "${P11_RELAX:-}" ] && export AILANG_RELAX_MODULES=1
fail=0
for m in "$@"; do
  [ -f "$m" ] || { echo "p12a: no such module in the workspace: $m"; fail=1; continue; }
  if [ "$mode" = check ]; then
    out=$(ailang check "$m" 2>&1); rc=$?
    if [ $rc -eq 0 ]; then echo "p12a: check $m ok"
    else
      first=$(echo "$out" | strip | grep -m1 -E 'Error|PAT_|PAR_|LDR0|MOD0|TC0|EFF' | cut -c1-400)
      echo "$out" | strip | tail -8; echo "p12a: check $m FAILED (exit $rc): ${first}"; fail=1
    fi
  elif [ "$mode" = run ]; then
    out=$(ailang run --caps "$RUN_CAPS" --ai-stub --entry main "$m" 2>&1); rc=$?
    echo "$out" | strip | grep -v -E '^(→|✓ Running|WARNING MOD010|  Auto-relaxed|  Running under)' | tail -12
    if [ $rc -eq 0 ]; then echo "p12a: run $m ok"
    else echo "$out" | strip | tail -6; echo "p12a: run $m FAILED (exit $rc)"; fail=1; fi
  else
    # P11_ALLOW_SKIPS=1 passes --allow-skips: a module whose contract
    # properties have no generator (exit_manifest.ail, pre-existing) otherwise
    # exits 1 with "0 failed"; the count line is still parsed and required.
    out=$(ailang test ${P11_ALLOW_SKIPS:+--allow-skips} "$m" 2>&1); rc=$?
    line=$(echo "$out" | strip | grep -E '^[0-9]+ tests:' | tail -1)
    # A here-string, not `echo | grep -q`: under pipefail an early-exiting grep
    # can SIGPIPE the writer and score a green run red (the P0.3 mutgate trap).
    if [ $rc -eq 0 ] && grep -qE '^[0-9]+ tests: [0-9]+ passed, 0 failed' <<<"$out"; then
      echo "p12a: test $m ok -- $line"
    else
      echo "$out" | strip | grep -E 'FAIL|Error|error|tests:' | tail -12; echo "p12a: test $m FAILED (exit $rc; $line)"; fail=1
    fi
  fi
done
exit $fail
