--[[
strip-dead-anchors.lua — bundled pandoc filter for tools/rmsend.

Markdown notes accumulate stale "[text](#some-heading)" links as headings get
renamed. Browsers and LaTeX render those as dead links and move on; the typst
engine aborts the whole document with "label ... does not exist". This filter
keeps the link text and drops the jump whenever the target id is absent, so one
stale anchor cannot cost the reader the entire PDF.
--]]

local ids = {}

local function record(el)
  if el.identifier and el.identifier ~= "" then
    ids[el.identifier] = true
  end
end

function Pandoc(doc)
  -- Pass 1: every anchorable id in the document. Header ids are already
  -- auto-generated by the reader by the time filters run.
  doc:walk {
    Header = record,
    Div = record,
    Span = record,
    CodeBlock = record,
    Code = record,
    Table = record,
    Figure = record,
  }

  -- Pass 2: demote links whose "#target" was never defined.
  return doc:walk {
    Link = function(link)
      local anchor = link.target:match("^#(.+)$")
      if anchor and not ids[anchor] then
        return pandoc.Span(link.content)
      end
    end,
  }
end
