#!/usr/bin/env bash
# 031 PLAN-001 P1.2d: type-check / test / run the files batch D owns under the operator's
# masked-files ruling (PLAN-001 §3 P1.2) -- scripts/dst/compose_live_exec.ail,
# declared_vs_performed.ail, herdr_graded_dst.ail and the eight scripts/verify_* herdr
# files -- against COMMITTED HEAD (plan §0 item 13), in a throwaway workspace. Run from a
# repo root (the primary or a mutgate clone):
#   p12d_core_check.sh check <module.ail>...     ailang check each; exit 1 on any failure
#   p12d_core_check.sh test  <module.ail>...     ailang test each; "0 failed" required
#   p12d_core_check.sh run   <module.ail> [caps] [args...]  ailang run --ai-stub --entry main
#   p12d_core_check.sh suite [case...]           RUN the eleven masked files as their Makefile /
#                                                runner recipes do, asserting the same markers and
#                                                witnesses (all cases, or the named ones)
#   P11_RELAX=1   sets AILANG_RELAX_MODULES=1 (scripts/ module names do not match paths)
#
# Derived from evidence/P1.2a/p12a_core_check.sh, with ONE CHANGE OF SOURCE: src/, scripts/,
# tools/ and every package come from `git archive HEAD` (never the working tree, which
# other parts are editing), and only P1.2d's own paths -- packages/motoko-ext-compose,
# packages/motoko-ext-herdr and the eleven masked files -- are overlaid from the cwd's
# working tree. The registry is generated by the real template over the packages that
# are 8.0 at HEAD plus compose and herdr; the rest stay 7.4 until their batches land and
# are present only as import targets. scratchpad is the real package (8.0 at HEAD).
set -uo pipefail
mode="${1:-}"; shift || true
{ { [ "$mode" = check ] || [ "$mode" = test ] || [ "$mode" = run ]; } && [ $# -ge 1 ]; } || [ "$mode" = suite ] \
  || { echo "usage: $0 check|test <module.ail>... | run <module.ail> [caps] [args...] | suite [case...]" >&2; exit 2; }
RUN_CAPS=""; RUN_ARGS=()
if [ "$mode" = run ]; then RUN_CAPS="${2:-IO}"; RUN_ARGS=("${@:3}"); set -- "$1"; fi
R=$(pwd)
T=$(mktemp -d "${TMPDIR:-/tmp}/p12dcore.XXXXXX"); trap 'rm -rf "$T"' EXIT
OWN="packages/motoko-ext-compose packages/motoko-ext-herdr scripts/dst/compose_live_exec.ail scripts/dst/declared_vs_performed.ail scripts/dst/herdr_graded_dst.ail scripts/verify_delegate_kind_required.ail scripts/verify_exit_intent.ail scripts/verify_herdr_delegate_wait.ail scripts/verify_herdr_orchestrator.ail scripts/verify_mot131_early_answer.ail scripts/verify_mot133_owner_tag.ail scripts/verify_mot136_dagr_producer.ail scripts/verify_mot137_dagr_pane.ail"
mkdir -p "$T/head"
git archive HEAD src scripts tools packages | tar -x -C "$T/head"
for o in $OWN; do rm -rf "$T/head/$o"; mkdir -p "$T/head/$(dirname "$o")"; cp -r "$o" "$T/head/$o"; done
find "$T/head/packages" -name ailang.lock -delete
H="$T/head"
PKGS=""
for d in "$H"/packages/motoko-ext-*; do
  p=$(basename "$d")
  [ "$p" = motoko-ext-abi ] && continue
  grep -q 'motoko_ext_abi" = {[^}]*version = "8.0"' "$d/ailang.toml" 2>/dev/null && PKGS="$PKGS $p"
done
echo "p12d: registry over 8.0 packages at HEAD + batch D:$PKGS"
mkdir -p "$T/deps/motoko-ext-abi" "$T/deps/motoko_ext_conformance/fixtures" "$T/deps/motoko-ext-scratchpad"
deps=""; exts=""
for d in "$H"/packages/motoko-ext-*; do
  p=$(basename "$d"); [ "$p" = motoko-ext-abi ] && continue
  [ -f "$d/ailang.toml" ] || continue
  cp -r "$d" "$T/deps/$p"
  # re-point path dependencies at the workspace copies
  sed -i -E 's#path = "\.\./(motoko[-_a-z]*)"#path = "../\1"#' "$T/deps/$p/ailang.toml"
  name=$(sed -nE 's/^name = "(.*)"/\1/p' "$d/ailang.toml" | head -1)
  ver=$(sed -nE 's/^version = "(.*)"/\1/p' "$d/ailang.toml" | head -1)
  case "$name" in sunholo/motoko_ext_scratchpad) continue;; esac
  deps="$deps
\"$name\" = { path = \"deps/$p\" }"
  case " $PKGS " in *" $p "*) exts="$exts\"$name@$ver\", ";; esac
done
cp "$H"/packages/motoko-ext-abi/types.ail "$H"/packages/motoko-ext-abi/ailang.toml "$T/deps/motoko-ext-abi/"
cp "$H"/packages/motoko_ext_conformance/ailang.toml "$H"/packages/motoko_ext_conformance/invariants.ail \
   "$H"/packages/motoko_ext_conformance/harness.ail "$T/deps/motoko_ext_conformance/"
cp "$H"/packages/motoko_ext_conformance/fixtures/reject_fixtures.ail "$T/deps/motoko_ext_conformance/fixtures/"
( cd "$H" && find src scripts tools -name '*.ail' -print0 | while IFS= read -r -d '' f; do
    mkdir -p "$T/$(dirname "$f")"; cp "$f" "$T/$f"; done )

# scratchpad (packages/motoko_scratchpad, batch B) is 8.0 at HEAD since ca689e29: the
# REAL package, not P1.1's stand-in, and it is registered like every other 8.0 package.
rm -rf "$T/deps/motoko-ext-scratchpad"; cp -r "$H/packages/motoko_scratchpad" "$T/deps/motoko-ext-scratchpad"
find "$T/deps/motoko-ext-scratchpad" -name ailang.lock -delete
sp_ver=$(sed -nE 's/^version = "(.*)"/\1/p' "$T/deps/motoko-ext-scratchpad/ailang.toml" | head -1)
grep -q 'motoko_ext_abi" = {[^}]*version = "8.0"' "$T/deps/motoko-ext-scratchpad/ailang.toml" \
  && exts="$exts\"sunholo/motoko_ext_scratchpad@$sp_ver\", "

cat > "$T/ailang.toml" <<TOML
[package]
name = "local/p12dcore"
version = "0.1.0"
edition = "1"
module_prefix = "src"
ailang = ">=0.33.0"

[dependencies]
"sunholo/motoko_ext_abi" = { path = "deps/motoko-ext-abi" }
"sunholo/motoko_ext_conformance" = { path = "deps/motoko_ext_conformance" }
"sunholo/motoko_ext_scratchpad" = { path = "deps/motoko-ext-scratchpad" }$deps

[extensions]
packages = [${exts%, }]
config_import = "src/core/config.RuntimeConfig"
hooks_import = "pkg/sunholo/motoko_ext_abi/types.ExtensionHooks"
capability_import = "pkg/sunholo/motoko_ext_abi/types.Capability"
entry_import = "pkg/sunholo/motoko_ext_abi/types.ExtEntry"
normalize_import = "src/core/ext/registry_normalize"
registry_import = "pkg/sunholo/motoko_ext_abi/types.ExtRegistry"
output = "src/core/ext/registry_generated.ail"
effects = ["AI", "Clock", "Env", "FS", "IO", "Net", "Process", "Rand", "SharedMem", "Stream", "Trace"]

[effects]
max = ["IO", "Env", "AI", "Net", "FS", "Process", "SharedMem", "Clock", "Stream", "SharedIndex", "Rand", "Trace"]
TOML

# Scripts write run artifacts under a cwd-relative .ailang/ (present in the
# repo, absent from a fresh workspace).
mkdir -p "$T/.ailang"
cd "$T"
ailang lock > lock.log 2>&1 || { tail -5 lock.log; echo "p12d: ailang lock failed in the workspace"; exit 1; }
python3 "$R/tools/ext_registry_gen/generate.py" --config ailang.toml > gen.log 2>&1 \
  || { tail -5 gen.log; echo "p12d: registry generation failed"; exit 1; }

strip() { sed -E 's/\x1b\[[0-9;]*[a-zA-Z]//g' | grep -v -E '^(Warning: dependency|Run .ailang lock.)'; }
[ -n "${P11_RELAX:-}" ] && export AILANG_RELAX_MODULES=1
fail=0
if [ "$mode" = suite ]; then
  FULL=IO,Env,FS,AI,Process,Net,SharedMem,Clock,Stream,Trace,Rand   # Makefile herdr_graded / compose_live_exec
  GATE=Net,AI,SharedMem,IO,Env,Clock,FS,Process,Stream              # Makefile HERDR_GATE_CAPS
  WITHHELD=IO,AI,Net,SharedMem,Clock,Stream,Trace,Rand             # run_declared_vs_performed.sh WITHHELD_CAPS
  # NO_PANE: this workspace may run inside a herdr pane; the registrations must not see it.
  NO_PANE="env -u HERDR_ENV -u HERDR_PANE_ID -u HERDR_BIN_PATH -u HERDR_ORCHESTRATOR AILANG_RELAX_MODULES=1"
  want() { [ $# -eq 0 ] && return 0; for w in "${SUITE_ONLY[@]}"; do [ "$w" = "$1" ] && return 0; done; return 1; }
  SUITE_ONLY=("$@")
  # case <label> <fixed string that must appear> <fixed string that must NOT appear, or -> <command...>
  case_run() {
    local label=$1 must=$2 mustnot=$3; shift 3
    [ ${#SUITE_ONLY[@]} -eq 0 ] || want "$label" || return 0
    "$@" < /dev/null > run.out 2>&1; local rc=$?
    local ok=1
    [ $rc -eq 0 ] || ok=0
    grep -qF -- "$must" run.out || ok=0
    [ "$mustnot" = - ] || { grep -qF -- "$mustnot" run.out && ok=0; }
    if [ $ok -eq 1 ]; then echo "p12d: run $label ok -- $(grep -F -- "$must" run.out | head -1 | cut -c1-160)"
    else strip < run.out | grep -v -E 'WARNING MOD010|Auto-relaxed|Running under|^→|^✓' | tail -8
         echo "p12d: run $label FAILED (exit $rc; want '$must'${mustnot:+, not '$mustnot'})"; fail=1; fi
  }
  M=scripts/dst/declared_vs_performed.ail
  case_run compose_live_exec 'compose_live_exec PASS' - \
    ailang run --caps $FULL --entry main scripts/dst/compose_live_exec.ail
  case_run herdr_graded_dst 'HERDR-GRADED' - \
    env -u HERDR_DELEGATE_DEPTH -u HERDR_MAX_DELEGATE_DEPTH -u HERDR_DELEGATE_KIND -u HERDR_ALLOWED_KINDS \
      -u HERDR_REAP_ON_EXIT -u HERDR_CHECK_WAIT_MS -u HERDR_START_TIMEOUT_MS -u HERDR_MAX_OUTPUT_CHARS \
      -u HERDR_MOTOKO_SCRIPT -u HERDR_DAGR_PLAN -u HERDR_DAGR_SETTLE_ON_EXIT -u HERDR_SWEEP_SETTLE -u HERDR_SWEEP_STALE \
      HERDR_ENV=1 HERDR_BIN_PATH=/usr/local/bin/herdr HERDR_PANE_ID=w9:p0 HERDR_ORCHESTRATOR=off \
      HERDR_DAGR_PANE=0 MOTOKO_SESSION_MS=900 \
      HERDR_DELEGATE_DIR=./.tmp-herdr-graded/dlg MOTOKO_DAGR_DIR=./.tmp-herdr-graded/dagr \
      ailang run --caps $FULL --ai-stub --entry main scripts/dst/herdr_graded_dst.ail
  for v in verify_delegate_kind_required verify_exit_intent verify_herdr_delegate_wait verify_mot131_early_answer \
           verify_mot133_owner_tag verify_mot136_dagr_producer verify_mot137_dagr_pane verify_herdr_orchestrator; do
    case_run $v 'OK' 'FAIL' \
      env -u HERDR_ORCHESTRATOR AILANG_RELAX_MODULES=1 ailang run --caps $GATE --ai-stub --entry main scripts/$v.ail
    rm -rf ./.tmp-herdr-orch
  done
  case_run verify_herdr_delegate_wait.print_fixtures 'FIXTURE ' - \
    env AILANG_RELAX_MODULES=1 ailang run --caps $GATE --ai-stub --entry print_fixtures scripts/verify_herdr_delegate_wait.ail
  # declared_vs_performed: batch D's arms, with run_declared_vs_performed.sh's caps and witnesses
  W='REACHED COMPLETION witness='
  case_run dvp.compose_pre_step  "[compose_pre_step] ${W}dvp_witness|installed=compose+dvp_witness" - $NO_PANE ailang run --caps $WITHHELD --entry compose_pre_step $M
  case_run dvp.compose_budget    "[compose_budget] ${W}4242" - $NO_PANE ailang run --caps $WITHHELD --entry compose_budget $M
  case_run dvp.compose_solver    "[compose_solver] ${W}dvp-solver-witness" - $NO_PANE ailang run --caps $WITHHELD --entry compose_solver $M
  case_run dvp.compose_intercept_noninline "[compose_intercept_noninline] ${W}dvp-intercept-witness" - $NO_PANE ailang run --caps $WITHHELD --entry compose_intercept_noninline $M
  case_run dvp.compose_intercept_inline "[compose_intercept_inline] REACHED COMPLETION" - $NO_PANE ailang run --caps $WITHHELD --entry compose_intercept_inline $M
  case_run dvp.compose_tool_handle_threading "[compose_tool_handle_threading] ${W}clock_now;clock_now;" - \
    $NO_PANE ailang run --caps IO,AI,Net,SharedMem,Clock,Stream,Trace,Rand,Env,FS,Process --entry compose_tool_handle_threading $M
  case_run dvp.compose_intercept_threading "[compose_intercept_threading] ${W}clock_now;dir_make(tmp);file_write(tmp/inline_7.ail);path_stat(tmp/inline_7.ail);file_remove(tmp/inline_7.ail);" - \
    $NO_PANE ailang run --caps IO,AI,Net,SharedMem,Clock,Stream,Trace,Rand,Env,FS,Process --entry compose_intercept_threading $M
  for e in compose herdr; do
    case_run dvp.reg_$e "[reg_$e] REACHED COMPLETION" - $NO_PANE ailang run --caps $FULL --entry reg_$e $M
    case_run dvp.budget_$e "[budget_$e] ${W}4242" - $NO_PANE ailang run --caps $FULL --entry budget_$e $M
  done
  exit $fail
fi
for m in "$@"; do
  [ -f "$m" ] || { echo "p12d: no such module in the workspace: $m"; fail=1; continue; }
  if [ "$mode" = check ]; then
    out=$(ailang check "$m" 2>&1); rc=$?
    if [ $rc -eq 0 ]; then echo "p12d: check $m ok"
    else
      first=$(echo "$out" | strip | grep -m1 -E 'Error|PAT_|PAR_|LDR0|MOD0|TC0|EFF' | cut -c1-400)
      echo "$out" | strip | tail -8; echo "p12d: check $m FAILED (exit $rc): ${first}"; fail=1
    fi
  elif [ "$mode" = run ]; then
    out=$(ailang run --caps "$RUN_CAPS" --ai-stub --entry main "$m" ${RUN_ARGS[@]+"${RUN_ARGS[@]}"} 2>&1); rc=$?
    echo "$out" | strip | grep -v -E '^(→|✓ Running|WARNING MOD010|  Auto-relaxed|  Running under)' | tail -12
    if [ $rc -eq 0 ]; then echo "p12d: run $m ok"
    else echo "$out" | strip | tail -6; echo "p12d: run $m FAILED (exit $rc)"; fail=1; fi
  else
    # P11_ALLOW_SKIPS=1 passes --allow-skips: a module whose contract
    # properties have no generator (exit_manifest.ail, pre-existing) otherwise
    # exits 1 with "0 failed"; the count line is still parsed and required.
    out=$(ailang test ${P11_ALLOW_SKIPS:+--allow-skips} "$m" 2>&1); rc=$?
    line=$(echo "$out" | strip | grep -E '^[0-9]+ tests:' | tail -1)
    # A here-string, not `echo | grep -q`: under pipefail an early-exiting grep
    # can SIGPIPE the writer and score a green run red (the P0.3 mutgate trap).
    if [ $rc -eq 0 ] && grep -qE '^[0-9]+ tests: [0-9]+ passed, 0 failed' <<<"$out"; then
      echo "p12d: test $m ok -- $line"
    else
      echo "$out" | strip | grep -E 'FAIL|Error|error|tests:' | tail -12; echo "p12d: test $m FAILED (exit $rc; $line)"; fail=1
    fi
  fi
done
exit $fail
