[package]
name = "sunholo/motoko_omnigraph"
version = "0.1.0"
edition = "1"
module_prefix = "src"

[exports]
modules = ["src/core/ext/omnigraph/omnigraph"]

[dependencies]
"sunholo/motoko_core" = { path = "../.." }

[effects]
max = ["Process", "FS", "IO", "Env"]
