[package]
name = "sunholo/motoko_mcp"
version = "0.1.0"
edition = "1"
module_prefix = "src"

[exports]
modules = [
  "src/core/ext/mcp/types",
  "src/core/ext/mcp/exec",
  "src/core/ext/mcp/resolve"
]

[dependencies]
"sunholo/motoko_core" = { path = "../.." }

[effects]
max = ["Process", "Env", "IO"]
